# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_matrixaggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixaggregation',
            name='id_zone',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='map.Area'),
            preserve_default=False,
        ),
    ]
