# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_matrixaggregation_id_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.IntegerField()),
                ('area', models.CharField(max_length=3)),
                ('count', models.IntegerField()),
                ('fortnight', models.IntegerField()),
                ('month', models.IntegerField()),
                ('boatType', models.TextField()),
                ('id_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Area')),
            ],
        ),
        migrations.RemoveField(
            model_name='matrixaggregation',
            name='id_zone',
        ),
        migrations.DeleteModel(
            name='MatrixAggregation',
        ),
    ]
