# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20160519_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areahand',
            name='area',
            field=models.CharField(max_length=3),
        ),
    ]
