# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20160519_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaHand',
        ),
    ]
