# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_areahand_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaHand',
        ),
    ]
