# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_delete_areahand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=3)),
                ('count', models.IntegerField()),
                ('fortnight', models.IntegerField()),
                ('month', models.IntegerField()),
                ('boatType', models.TextField()),
                ('year', models.IntegerField()),
                ('activity', models.IntegerField()),
            ],
        ),
    ]
