# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_delete_clusteraden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterAden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barLong', models.FloatField()),
                ('barLat', models.FloatField()),
                ('rayon', models.FloatField()),
                ('weight', models.FloatField()),
                ('nbDays', models.FloatField()),
                ('month', models.FloatField()),
                ('year', models.FloatField()),
                ('ref', models.CharField(max_length=10)),
            ],
        ),
    ]
