# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_clusteraden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClusterAden',
        ),
    ]
