# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_clusteraden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
