# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_delete_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=3)),
                ('min_lat', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('min_lon', models.FloatField()),
                ('max_lon', models.FloatField()),
            ],
        ),
    ]
