# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_areahand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClusterAden',
        ),
    ]
